PREFIX dbrik: <http://id.dbpedia.org/resource/Kategori:>
PREFIX dboi: <http://id.dbpedia.org/ontology/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbpropi: <http://id.dbpedia.org/property/>

SELECT DISTINCT
    STR(?nama) AS ?nama
    IF(?namaPartai = ?namaPartai,
        STR(?namaPartai),
        REPLACE(REPLACE(STR(?partai_), "_", " "), "http://id.dbpedia.org/resource/", "")) AS ?partai
    REPLACE(REPLACE(?namaKotaLahir, "Kabupaten ", ""), "Kota ", "") AS ?kota_lahir
    REPLACE(REPLACE(?namaKota, "Kabupaten ", ""), "Kota ", "") AS ?kota_terkait
WHERE {
    ?a ?b dbrik:Aktivis_Indonesia;
       rdfs:label ?nama.
    
    OPTIONAL { 
        ?a dbo:birthPlace ?kotaLahir.
        FILTER NOT EXISTS { ?kotaLahir a dbo:Province }
        FILTER(!CONTAINS(STR(?kotaLahir), "Indonesia"))
        FILTER(!CONTAINS(STR(?kotaLahir), "Hindia_Belanda"))
        FILTER(!CONTAINS(STR(?kotaLahir), "India"))
        ?kotaLahir rdfs:label ?namaKotaLahir.
    }
    OPTIONAL {
        ?a dbo:wikiPageWikiLink ?partai_.
        OPTIONAL{ ?partai_ rdfs:label ?namaPartai. }
        FILTER( CONTAINS( STR(?partai_), "Partai") && !CONTAINS( STR(?partai_), "Tokoh") )
    }
    OPTIONAL {
        ?a dbo:wikiPageWikiLink ?kota.
        ?kota rdfs:label ?namaKota.
        ?c dbpropi:kota ?kota.
        FILTER NOT EXISTS { ?kota a dbo:Province }
    }
}
LIMIT 200